<h3 style="font-family:monospace">Data Types in NumPy :</h3>

<ul style="font-family:monospace">
    <li><span style="color:blue">NumPy has some extra data types, and refer to data types with <span style="color:red">one character</span> like <span style="color:red">i</span> for <span style="color:red">integers</span>, <span style="color:red">u</span> for <span style="color:red">unsigned integers</span> etc.</span></li>
</ul>

<h3 style="font-family:monospace">List of Data Types in NumPy :</h3>

<ul style="font-family:monospace">
    <li><span style="color:blue"><span style="color:red">i</span> - integer</span></li>
    <li><span style="color:blue"><span style="color:red">b</span> - boolean</span></li>
    <li><span style="color:blue"><span style="color:red">u</span> - unsigned integer</span></li>
    <li><span style="color:blue"><span style="color:red">c</span> - complex float</span></li>
    <li><span style="color:blue"><span style="color:red">m</span> - timedelta</span></li>
    <li><span style="color:blue"><span style="color:red">M</span> - datetime</span></li>
    <li><span style="color:blue"><span style="color:red">O</span> - object</span></li>
    <li><span style="color:blue"><span style="color:red">S</span> - string</span></li>
    <li><span style="color:blue"><span style="color:red">U</span> - unicode string</span></li>
    <li><span style="color:blue"><span style="color:red">V</span> - fixed chunk of memory for other type ( void )</span></li>
</ul>

<h3 style="font-family:monospace">Checking the Data Type of an Array :</h3>

<ul style="font-family:monospace">
    <li><span style="color:blue">The NumPy array object has a property called <span style="color:red">dtype</span> that returns the <span style="color:red">data type</span> of the array.</span></li>
</ul>

In [4]:
import numpy as np    # Importing NumPy Libary

In [4]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)

int32


In [6]:
arr = np.array(['key', 'door', 'lock', 'window'])
print(arr.dtype)

<U6


<h3 style="font-family:monospace">Creating Arrays With a Defined Data Type :</h3>

In [9]:
arr = np.array([1, 2, 3, 4, 5], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


<p style="font-family:monospace">For <span style="color:red">i</span>, <span style="color:red">u</span>, <span style="color:red">f</span>, <span style="color:red">S</span> and <span style="color:red">U</span> we can define size as well.</p>

In [5]:
arr = np.array([1, 2, 3, 4, 5], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


<h3 style="font-family:monospace">What if a Value Can Not Be Converted ?</h3>

<p style="font-family:monospace">A non integer string like '<span style="color:red">a</span>' can not be converted to <span style="color:red">integer</span> (will raise an error):</p>

In [7]:
arr = np.array(['a', '2', 'b', '4', 'c'], dtype='i')
print(arr)

ValueError: invalid literal for int() with base 10: 'a'

<p style="font-family:monospace; color:blue"><span style="font-weight:bold;color:black">ValueError :</span> In Python ValueError is raised when the type of passed argument to a function is unexpected/incorrect.</p>

<h3 style="font-family:monospace">Converting Data Type on Existing Arrays :</h3>

<ul style="font-family:monospace">
    <li><span style="color:blue">The best way to change the data type of an existing array, is to make a copy of the array with the <span style="color:red">astype()</span> method.</span></li>
    <li><span style="color:blue">The <span style="color:red">astype()</span> function creates a <span style="color:red">copy of the array</span>, and allows you to specify the <span style="color:red">data type as a parameter</span>.</span></li>
    <li><span style="color:blue">The data type can be specified using a <span style="color:red">string</span>, like '<span style="color:red">f</span>' for <span style="color:red">float</span>, '<span style="color:red">i</span>' for <span style="color:red">integer</span> etc. or you can use the data type directly like <span style="color:red">float</span> for <span style="color:red">float</span> and <span style="color:red">int</span> for <span style="color:red">integer</span>.</span></li>
</ul>

In [8]:
arr = np.array([1.1, 2.2, 3.3, 4.4, 5.5])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3 4 5]
int32


In [9]:
arr = np.array([1.1, 2.2, 3.3, 4.4, 5.5])
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3 4 5]
int32


In [10]:
arr = np.array([1, 0, 4])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool
