<h3 style="font-family:monospace">Creating a NumPy ndarray Object :</h3>

<ul style="font-family: monospace">
    <li><span style="color:blue">NumPy is used to <span style="color:red">working with arrays</span>.</span></li>
    <li><span style="color:blue">The array object in NumPy is called <span style="color:red">ndarray</span>.</span></li>
    <li><span style="color:blue">We can create a NumPy <span style="color:red">ndarray</span> object by using the <span style="color:red">array()</span> function.</span></li>
    <li><span style="color:blue">Unlike lists, all elements of a NumPy array are of the <span style="color:red">same type</span>.</span></li>
</ul>

In [2]:
import numpy as np    # Import NumPy Libary

In [7]:
arr = np.array([1, 2, 3, 4, 5])    # Passing a List
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


<p style="font-family:monospace;color:blue;background-color: whitesmoke; padding:10px;border-radius:5px"><span style="color:black;font-weight:bolder">type() :</span> This built-in Python function tells us the <span style="color:red">type of the object</span> passed to it. Like in above code it shows that <span style="color:red">arr</span> is <span style="color:red">numpy.ndarray </span>type.</p>

<p style="font-family:monospace;color:black;">To create an <span style="color:red">ndarray</span>, we can pass a <span style="color:red">list</span>, <span style="color:red">tuple</span> or any <span style="color:red">array-like object</span> into the <span style="color:red">array()</span> method, and it will be converted into an <span style="color:red">ndarray</span>:</p>

In [6]:
arr = np.array((1, 2, 3, 4, 5))    # Passing a Tuple
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [23]:
intarr = np.array([1, 2, 3, 4])    # Creating Array of Integer 
floatarr = np.array([1.1, 2.2, 3.3, 4.4])    # Creating Array of Float

<p style="font-family:monospace;color:black;">If we mix <span style="color:red">ints</span> and <span style="color:red">floats</span>, NumPy defaults to <span style="color:red">array of floats</span>.</p>

In [27]:
arr = np.array([1, 2.2, 3.3, 4])
print(arr)

[1.  2.2 3.3 4. ]


<p style="font-family:monospace;color:black;">If we wish we can also specify the <span style="color:red">type</span>.</p>

In [30]:
a = np.array([1, 2, 3, 4], int)    
b = np.array([1.1, 2.2, 3.3, 4.4], float)
c = np.array([1.1, 2.2, 3.3, 4.4], int)
print(a)
print(b)
print(c)

[1 2 3 4]
[1.1 2.2 3.3 4.4]
[1 2 3 4]


<p style="font-family:monospace;color:black;"><span style="color:red">Array of complex</span> numbers also be created.</p>

In [29]:
comarr = np.array([1, 2, 3, 4], complex)
print(comarr)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


<h3 style="font-family:monospace">Dimensions in Arrays :</h3>

<h3 style="font-family:monospace">0-D Arrays :</h3>

<li><span style="font-family:monospace;color:blue;"><span style="color:red">0-D arrays</span>, or <span style="color:red">Scalars</span>, are the elements in an array.</span></li>
<li><span style="font-family:monospace;color:blue;">Each value in an array is a <span style="color:red">0-D array</span>.</span></li>

In [9]:
arr = np.array(45)
print(arr)

45


<h3 style="font-family:monospace">1-D Arrays :</h3>

<li><span style="font-family:monospace;color:blue;">An array that has <span style="color:red">0-D arrays</span> as its elements is called <span style="color:red">uni-dimensional</span> or <span style="color:red">1-D arrays</span>.</span></li>

In [10]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


<h3 style="font-family:monospace">2-D Arrays :</h3>

<li><span style="font-family:monospace;color:blue;">An array that has <span style="color:red">1-D arrays</span> as its elements is called <span style="color:red">2-D arrays</span>.</span></li>
<li><span style="font-family:monospace;color:blue;">These are often used to represent <span style="color:red">matrix</span> or <span style="color:red">2nd order tensors</span>.</span></li>

In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


<h3 style="font-family:monospace">3-D Arrays :</h3>

<li><span style="font-family:monospace;color:blue;">An array that has <span style="color:red">2-D arrays</span> as its elements is called <span style="color:red">3-D arrays</span>.</span></li>
<li><span style="font-family:monospace;color:blue;">These are often used to represent <span style="color:red">3nd order tensors</span>.</span></li>

In [13]:
arr = np.array([[[1, 2], [4, 5]], [[6, 7], [8, 9]]])
print(arr)

[[[1 2]
  [4 5]]

 [[6 7]
  [8 9]]]


<h3 style="font-family:monospace">Checking Number of Dimensions ?</h3>

<p style="font-family:monospace;color:black;">NumPy Arrays provides the <span style="color:red">ndim</span> attribute that returns an <span style="color:red">integer</span> that tells us <span style="color:red">how many dimensions the array have</span>.</p>

In [18]:
a = np.array(45)
b = np.array([1, 2, 3])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2], [4, 5]], [[6, 7], [8, 9]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


<h3 style="font-family:monospace">Higer Dimensional Array :</h3>

<li><span style="font-family:monospace;color:blue;">An array can have any number of dimensions.</span></li>
<li><span style="font-family:monospace;color:blue;">When the array is created, you can define the number of dimensions using the <span style="color:red">ndmin</span> argument.</span></li>

In [21]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)

[[[[[1 2 3 4]]]]]


<p style="font-family:monospace;color:black;">In this array the innermost dimension (<span style="color:red">5th dim</span>) has <span style="color:red">4 elements</span>, the <span style="color:red">4th dim</span> has <span style="color:red">1 element</span> that is the <span style="color:red">vector</span>, the <span style="color:red">3rd dim</span> has <span style="color:red">1 element</span> that is the <span style="color:red">matrix</span> with the <span style="color:red">vector</span>, the <span style="color:red">2nd dim</span> has <span style="color:red">1 element</span> that is <span style="color:red">3D array</span> and <span style="color:red">1st dim</span> has <span style="color:red">1 element</span> that is a <span style="color:red">4D array</span>.</p>