In [2]:
import numpy as np    # Import NumPy Libary

<h3 style="font-family:monospace">NumPy ufunc :</h3>

<ul style="font-family:monospace">
    <li><span style="color:blue">ufuncs stands for "<span style="color:red">Universal Functions</span>".</span></li>
    <li><span style="color:blue">Universal functions in Numpy are <span style="color:red">simple mathematical functions</span>.</span></li>
    <li><span style="color:blue">These functions include <span style="color:red">standard trigonometric functions</span>, functions for <span style="color:red">arithmetic operations</span>, <span style="color:red">handling complex numbers</span>, <span style="color:red">statistical functions</span>, etc.</span></li>
    <li><span style="color:blue">These functions operates on <span style="color:red">ndarray</span> (<span style="color:red">N-dimensional array</span>) <span style="color:red">object</span>.</span></li>
</ul>

<h3 style="font-family:monospace">Create Your Own ufunc :</h3>

<p style="font-family:monospace;color:blue;text-indent:24px;">To create your own ufunc, you have to define a <span style="color:red">function</span>, like you do with <span style="color:red">normal functions</span> in Python, then you add it to your <span style="color:red">NumPy ufunc library</span> with the <span style="color:red">frompyfunc()</span> method.</p>

<p style="font-family:monospace">The <span style="color:red">frompyfunc()</span> method takes the following arguments :</p>
<ol style="font-family:monospace">
    <li><span style="color:blue"><span style="color:red">function</span> <span style="color:black">-</span> the name of the function.</span></li>
    <li><span style="color:blue"><span style="color:red">inputs</span> <span style="color:black">-</span> the number of input arguments (arrays).</span></li>
    <li><span style="color:blue"><span style="color:red">outputs</span> <span style="color:black">-</span> the number of output arrays.</span></li>
</ol>

<h3 style="font-family:monospace;font-weight:bold;">Example:</h3>

In [9]:
def add(x, y):
    return x+y

arr = np.frompyfunc(add, 2, 1)

print(arr([1, 2, 3, 4], [5, 6 ,7, 8]))

[6 8 10 12]


<h3 style="font-family:monospace">Check if a Function is a ufunc :</h3>

In [10]:
print(type(arr))

<class 'numpy.ufunc'>


<h3 style="font-family:monospace">ufunc Simple Arithmetic :</h3>

In [20]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

print(np.add(arr1, arr2))

[ 7  9 11 13 15]


<p style="font-family:monospace">The <span style="color:red">add()</span> function <span style="color:red">sums</span> the content of two arrays, and return the results in a <span style="color:red">new array</span>.</p>

In [21]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

print(np.subtract(arr1, arr2))

[-5 -5 -5 -5 -5]


<p style="font-family:monospace">The <span style="color:red">subtract()</span> function <span style="color:red">subtracts</span> the values from one array with the values from another array, and return the results in a <span style="color:red">new array</span>.</p>

In [26]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

print(np.multiply(arr1, arr2))

[ 6 14 24 36 50]


<p style="font-family:monospace">The <span style="color:red">multiply()</span> function <span style="color:red">multiplies</span> the values from one array with the values from another array, and return the results in a <span style="color:red">new array</span>.</p>

In [27]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

print(np.divide(arr1, arr2))

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


<p style="font-family:monospace">The <span style="color:red">divide()</span> function <span style="color:red">divides</span> the values from one array with the values from another array, and return the results in a <span style="color:red">new array</span>.</p>

In [30]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

print(np.mod(arr1, arr2))
print(np.remainder(arr1, arr2))

[1 2 3 4 5]
[1 2 3 4 5]


<p style="font-family:monospace">Both the <span style="color:red">mod()</span> and the <span style="color:red">remainder()</span> functions return the <span style="color:red">remainder</span> of the values in the first array corresponding to the values in the second array, and return the results in a <span style="color:red">new array</span>.</p>

In [29]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

print(np.divmod(arr1, arr2))

(array([0, 0, 0, 0, 0]), array([1, 2, 3, 4, 5]))


<p style="font-family:monospace">The <span style="color:red">divmod()</span> function return both the <span style="color:red">quotient</span> and the <span style="color:red">mod</span>. The return value is <span style="color:red">two arrays</span>, the first array contains the <span style="color:red">quotient</span> and second array contains the <span style="color:red">mod</span>.</p>

In [31]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

print(np.power(arr1, arr2))

[      1     128    6561  262144 9765625]


<p style="font-family:monospace">The <span style="color:red">power()</span> function rises the values from the first array to the power of the values of the second array, and return the results in a <span style="color:red">new array</span>.</p>

In [32]:
arr = np.array([-1, 2, -3, 4, -5])

print(np.absolute(arr))
print(np.abs(arr))

[1 2 3 4 5]
[1 2 3 4 5]


<p style="font-family:monospace">Both the <span style="color:red">absolute()</span> and the <span style="color:red">abs()</span> functions do the same absolute operation.</p>

<h3 style="font-family:monospace">ufunc Rounding Decimals :</h3>

In [36]:
print(np.trunc([34.5, -356.6]))
print(np.fix([34.5, -356.6]))

[  34. -356.]
[  34. -356.]


<p style="font-family:monospace">Both the <span style="color:red">trunc()</span> and the <span style="color:red">fix()</span> functions <span style="color:red">remove the decimals</span>, and return the <span style="color:red">float number closest to zero</span>.</p>

In [37]:
print(np.round(323.567, 2))

323.57


<p style="font-family:monospace">The <span style="color:red">around()</span> function <span style="color:red">increments preceding digit</span> or <span style="color:red">decimal</span> by <span style="color:red">1</span> if <span style="color:red">>=5</span> else <span style="color:red">do nothing</span>.</p>

In [42]:
print(np.floor([34.5, -356.6]))

[  34. -357.]


<p style="font-family:monospace">The <span style="color:red">floor()</span> function <span style="color:red">rounds off decimal to nearest lower integer</span>.</p>

In [45]:
print(np.ceil([34.5, -356.6]))

[  35. -356.]


<p style="font-family:monospace">The <span style="color:red">ceil()</span> function <span style="color:red">rounds off decimal to nearest upper integer</span>.</p>

<h3 style="font-family:monospace">ufunc Logs :</h3>

In [51]:
print(np.log2([1, 2, 3, 4, 5]))

[0.         1.         1.5849625  2.         2.32192809]


<p style="font-family:monospace">The <span style="color:red">log2()</span> function to perform log at the <span style="color:red">base 2</span>.</p>

In [47]:
print(np.log10([1, 2, 3, 4, 5]))

[0.         0.30103    0.47712125 0.60205999 0.69897   ]


<p style="font-family:monospace">The <span style="color:red">log10()</span> function to perform log at the <span style="color:red">base 10</span>.</p>

In [50]:
print(np.log([1, 2, 3, 4, 5]))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


<p style="font-family:monospace">The <span style="color:red">log()</span> function to perform log at the <span style="color:red">base e</span>.</p>

<h3 style="font-family:monospace">Log at Any Base :</h3>

<p style="font-family:monospace">NumPy does not provide any function to take <span style="color:red">log at any base</span>, so we can use the <span style="color:red">frompyfunc()</span> function along with inbuilt function <span style="color:red">math.log()</span> with <span style="color:red">two input parameters</span> and <span style="color:red">one output parameter</span> :</p>

In [53]:
from math import log    # Import math Libary for Log Class

In [54]:
nplog = np.frompyfunc(log, 2, 1)

print(nplog(100, 15))

1.7005483074552052


<h3 style="font-family:monospace">ufunc Summations :</h3>